# Generated by Django 6.0.2 on 2026-02-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
