# Generated by Django 6.0.2 on 2026-02-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_receiptitem_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['user__username'], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
