# Generated by Django 6.0.2 on 2026-02-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_add_customer_code_simple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='cbm',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Cubic meters', max_digits=10),
        ),
    ]
