# Generated by Django 6.0.2 on 2026-02-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_remove_receiptitem_quantity_receiptitem_cbm'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='container_number',
            field=models.CharField(blank=True, help_text='Container number', max_length=50),
        ),
        migrations.AddField(
            model_name='receipt',
            name='eta',
            field=models.DateField(blank=True, help_text='Estimated Time of Arrival', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='loading_date',
            field=models.DateField(blank=True, help_text='Loading date for shipment', null=True),
        ),
    ]
